"""add status and performer columns in applications table

Revision ID: 25437e61541a
Revises: 915c16ec60e3
Create Date: 2026-03-23 20:52:48.842715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25437e61541a'
down_revision: Union[str, Sequence[str], None] = '915c16ec60e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status  = sa.Enum('is_open', 'in_process', 'is_closed', 'is_confirmed', name='applicationstatus')
    status.create(op.get_bind())
    
    op.add_column('applications', sa.Column('status', status, server_default='is_open', nullable=False))
    op.add_column('applications', sa.Column('performer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applications', 'users', ['performer_id'], ['id'])

    tool_status = sa.Enum('in_storage', 'used', 'broken', 'used_up', name='toolstatus')
    tool_status.create(op.get_bind())

    op.add_column('tools', sa.Column('new_status', tool_status, nullable=True))
    op.drop_column('tools', 'status')
    op.alter_column('tools', 'new_status', new_column_name='status', nullable=False)
    op.alter_column('tools', 'status', 
                    server_default=sa.text("'in_storage'::toolstatus"),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'status',
               existing_type=sa.Enum('in_storage', 'used', 'broken', 'used_up', name='toolstatus'),
               type_=postgresql.ENUM('in_storage', 'used', 'broken', 'used_up', name='status'),
               existing_nullable=False,
               existing_server_default=sa.text("'in_storage'::status"))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'performer_id')
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###
