"""change primary key from int to str in tools

Revision ID: 27592a8aaeeb
Revises: fc09a81c6a3e
Create Date: 2026-03-14 17:44:04.292128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27592a8aaeeb'
down_revision: Union[str, Sequence[str], None] = 'fc09a81c6a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('storage_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('tools_storage_fkey'), 'tools', type_='foreignkey')
    op.create_foreign_key(None, 'tools', 'storages', ['storage_name'], ['name'])
    op.drop_column('tools', 'storage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('storage', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.create_foreign_key(op.f('tools_storage_fkey'), 'tools', 'storages', ['storage'], ['name'])
    op.drop_column('tools', 'storage_name')
    # ### end Alembic commands ###
