"""delete column id in roles 2

Revision ID: 517cdbfb0a2d
Revises: 621053594064
Create Date: 2026-03-11 00:02:57.678809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517cdbfb0a2d'
down_revision: Union[str, Sequence[str], None] = '621053594064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['role'])
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['role'])
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
