"""refactor tables

Revision ID: 668bb6a82ea7
Revises: 925bd5539204
Create Date: 2026-03-05 22:17:04.603110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '668bb6a82ea7'
down_revision: Union[str, Sequence[str], None] = '925bd5539204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('applications', 'deleted')
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('roles', 'deleted')
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'deleted')
    op.drop_column('users', 'roles.role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles.role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'role')
    op.add_column('roles', sa.Column('deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('roles', 'deleted_at')
    op.add_column('applications', sa.Column('deleted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'deleted_at')
    # ### end Alembic commands ###
