"""change users.cabinet column to foreign_key

Revision ID: 710c09193ea3
Revises: d4b857af91d5
Create Date: 2026-03-16 18:34:13.334833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710c09193ea3'
down_revision: Union[str, Sequence[str], None] = 'd4b857af91d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cabinets', ['name'])
    op.drop_constraint(op.f('users_role_name_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_name'], ['role'])
    op.create_foreign_key(None, 'users', 'cabinets', ['cabinet'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_name_fkey'), 'users', 'roles', ['role_name'], ['role'], ondelete='CASCADE')
    op.drop_constraint(None, 'cabinets', type_='unique')
    # ### end Alembic commands ###
