"""add law_open_admin_panel column to roles table

Revision ID: 9cfff11df3df
Revises: 32b8f73bf77c
Create Date: 2026-03-25 02:07:26.940829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfff11df3df'
down_revision: Union[str, Sequence[str], None] = '32b8f73bf77c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('law_open_admin_panel', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'law_open_admin_panel')
    # ### end Alembic commands ###
