"""add role table russain_name and css_style_class columns

Revision ID: b1ee18d93bbb
Revises: b31605c9643d
Create Date: 2026-03-15 17:58:42.138915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ee18d93bbb'
down_revision: Union[str, Sequence[str], None] = 'b31605c9643d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('russian_name', sa.String(), nullable=True))
    op.add_column('roles', sa.Column('css_style_class', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_role_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_name'], ['role'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_fkey'), 'users', 'roles', ['role'], ['role'])
    op.drop_column('users', 'role_name')
    op.drop_column('roles', 'css_style_class')
    op.drop_column('roles', 'russian_name')
    # ### end Alembic commands ###
