"""rename storages table to cabinets

Revision ID: d4b857af91d5
Revises: b1ee18d93bbb
Create Date: 2026-03-15 20:58:30.935214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4b857af91d5'
down_revision: Union[str, Sequence[str], None] = 'b1ee18d93bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.drop_constraint(op.f('tools_storage_name_fkey'), 'tools', type_='foreignkey')
    op.drop_table('storages')
    op.add_column('tools', sa.Column('cabinet_name', sa.String(), nullable=False))
    # op.drop_constraint(op.f('tools_storage_name_fkey'), 'tools', type_='foreignkey')
    op.create_foreign_key(None, 'tools', 'cabinets', ['cabinet_name'], ['name'])
    op.drop_column('tools', 'storage_name')
    op.alter_column('users', 'role_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tools', sa.Column('storage_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.create_foreign_key(op.f('tools_storage_name_fkey'), 'tools', 'storages', ['storage_name'], ['name'])
    op.drop_column('tools', 'cabinet_name')
    op.create_table('storages',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('storages_pkey')),
    sa.UniqueConstraint('name', name=op.f('storages_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('cabinets')
    # ### end Alembic commands ###
