"""create tools table

Revision ID: db390622c62d
Revises: 517cdbfb0a2d
Create Date: 2026-03-13 15:54:42.049062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db390622c62d'
down_revision: Union[str, Sequence[str], None] = '517cdbfb0a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storages',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tools',
    sa.Column('inventory_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('in_storage', 'used', 'broken', 'used_up', name='status'), server_default='in_storage', nullable=False),
    sa.Column('storage', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['storage'], ['storages.name'], ),
    sa.PrimaryKeyConstraint('inventory_number'),
    sa.UniqueConstraint('inventory_number')
    )
    op.add_column('roles', sa.Column('law_show_inventory', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('roles', sa.Column('law_add_inventory', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('roles', sa.Column('law_use_inventory', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('roles', sa.Column('law_delete_inventory', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'law_delete_inventory')
    op.drop_column('roles', 'law_use_inventory')
    op.drop_column('roles', 'law_add_inventory')
    op.drop_column('roles', 'law_show_inventory')
    op.drop_table('tools')
    op.drop_table('storages')
    # ### end Alembic commands ###
