"""change primary key from int to str in tools

Revision ID: fc09a81c6a3e
Revises: db390622c62d
Create Date: 2026-03-13 20:53:51.288530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc09a81c6a3e'
down_revision: Union[str, Sequence[str], None] = 'db390622c62d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'storages', ['name'])
    op.alter_column('tools', 'inventory_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'tools', ['inventory_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tools', type_='unique')
    op.alter_column('tools', 'inventory_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'storages', type_='unique')
    # ### end Alembic commands ###
